export const userInputs = [
  {
    id: "idNum",
    label: "ID Number",
    type: "text",
    required: true,
  },
  {
    id: "firstName",
    label: "First Name",
    type: "text",
    placeholder: "First Name",
    required: true,
  },
  {
    id: "lastName",
    label: "Last Name",
    type: "text",
    placeholder: "Last Name",
    required: true,
  },
  {
    id: "email",
    label: "School Email",
    type: "email",
    placeholder: "example@cit.edu",
  },
  {
    id: "department",
    label: "Department",
    type: "text",
    placeholder: "e.g., CCS",
    required: true,
  },
  {
    id: "role",
    label: "Role",
    type: "radio",
    options: ["Student", "Faculty", "Admin"],
    required: true,
  },
  {
    id: "password",
    label: "Password",
    type: "password",
  },
];

export const classInputs = [
  {
    id: "classCode",
    label: "Class Code",
    type: "text",
    placeholder: "e.g., CSIT000",
    required: true,
  },
  {
    id: "classDesc",
    label: "Course Description",
    type: "text",
    placeholder: "e.g., Programming 1",
    required: true,
  },
  {
    id: "classSec",
    label: "Class Section",
    type: "text",
    placeholder: "e.g., F0/G0",
    required: true,
  },
  {
    id: "classRoom",
    label: "Classroom",
    type: "text",
    placeholder: "e.g., GLE, NGE, etc.",
    required: true,
  },
  {
    id: "classType",
    label: "Type of Class",
    type: "radio",
    options: ["Lecture", "Lab", "Online"],
    required: true,
  },
  {
    id: "days",
    label: "Day/s of the Week",
    type: "text",
    placeholder: "e.g., Monday, Tuesday, Wednesday, etc.",
    options: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    required: true,
  },
  {
    id: "startTime",
    label: "Start Time",
    type: "time",
    placeholder: "Start Time",
    required: true,
  },
  {
    id: "endTime",
    label: "End Time",
    type: "time",
    placeholder: "End Time",
    required: true,
  },
  {
    id: "schoolYear",
    label: "School Year",
    type: "text",
    placeholder: "e.g., 2324",
    pattern: "^[0-9]{4}$",
    title: "Please enter a 4-digit year.",
    required: true,
  },
  {
    id: "semester",
    label: "Semester",
    type: "radio",
    options: ["First", "Second", "Midyear"],
    required: true,
  },
  {
    id: "ip_address",
    label: "IP Address",
    type: "text",
    placeholder: "IPv4",
  }, // Not required
];
